env: local
serverHttpPort: 8080
db:
  user: admin
  password: 12341234
  host: localhost
  port: 5432
  dbName: ecommerce
  enableSsl: false
  autoMigrate: true

redis:
  host: localhost:6379

auth:
  jwtPrivateKey: GfiXigSkLwFGXWXJY3qJzRahWUILE7YPeM3ryKmDA3wCGAC+zaerwKXrIKNEJBCL/zMHZvV7Qo9cC8vNYnoRdw==
  jwtPublicKey: AhgAvs2nq8Cl6yCjRCQQi/8zB2b1e0KPXAvLzWJ6EXc=
