version: '3.8'

volumes:
  postgres_data: {}

services:
  duchm_online-shop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP__DB__HOST=postgres
      - APP__REDIS__HOST=redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: docker.io/bitnami/postgresql:14
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=ecommerce
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=12341234

  redis:
    image: 'bitnami/redis:6.2'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
